[template]
src = "sogo.conf.tmpl"
dest = "/srv/etc/sogo.conf"
keys = [
    "SOGoProfileURL",
    "OCSFolderInfoURL",
    "OCSSessionsFolderURL",
    "SOGoIMAPServer",
    "SOGoSieveServer",
    "SOGoSieveScriptsEnabled",
    "SOGoMailingMechanism",
    "SOGoForceExternalLoginWithEmail",
    "SOGoUserSourcesMySql",
    "SOGoPageTitle",
    "SOGoLanguage",
    "SOGoTimeZone",
    "SOGoSuperUsernames",
    "SxVMemLimit",
    "WOWorkersCount",
    "SOGoMaximumPingInterval",
    "SOGoMaximumSyncInterval",
    "SOGoInternalSyncInterval",
    "SOGoMemcachedHost",
    "SOGoCacheCleanupInterval"
]
